-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: name-tests-test
    -   id: requirements-txt-fixer

-   repo: git://github.com/detailyang/pre-commit-shell
    sha: 1.0.2
    hooks:
    -   id: shell-lint
        files: announce_to_github.sh
