language: python

python:
  - "3.6"

before_install:
  - sudo apt-get update -yqq

install:
  - pip install -r message-api-schema-validator/requirements.txt

script:
  - pre-commit run --all-files --verbose
  - cd ./message-api-schema-validator && pytest

after_success:
  - chmod +x ./announce_to_github.sh
  - ./announce_to_github.sh
