language: python
python:
  - "3.6"

install:
  - pip install pylint
  - pip install -r requirements.txt
before_script:
  - pylint --errors-only ./message-api-schema-validator/schema_validator_test_suite.py
  - pylint --errors-only ./message-api-schema-validator/tests
script:
  - python message-api-scheme-validator/schema_validator_test_suite.py
