language: python

python:
  - "3.6"

before_install:
  - sudo apt-get update -yqq

install:
  - pip install -r requirements.txt

before_script:
  - pylint --errors-only ./message-api-schema-validator/schema_validator_test_suite.py
  - pylint --errors-only ./message-api-schema-validator/tests

script:
  - pre-commit run --all-files --verbose
  - python message-api-schema-validator/schema_validator_test_suite.py

after_success:
  - chmod +x ./update_taxonomy_data.sh
  - ./update_taxonomy_data.sh
  - chmod +x ./announce_to_github.sh
  - ./announce_to_github.sh
