language: python

python:
  - "3.6"

before_install:
  - sudo apt-get update -yqq

install:
  - pip install -r message-api-schema-validator/requirements.txt

before_script:
  - pylint --errors-only ./message-api-schema-validator/rdss_schema
  - pylint --errors-only ./message-api-schema-validator/tests

script:
  - pre-commit run --all-files --verbose
  - cd ./message-api-schema-validator && pytest

after_success:
  - chmod +x ./update_taxonomy_data.sh
  - ./update_taxonomy_data.sh
  - chmod +x ./announce_to_github.sh
  - ./announce_to_github.sh
